//
//  V4AuthenticationService.swift
//  TMDb
//
//  Copyright © 2026 Adam Young.
//

import Foundation

///
/// Provides an interface for authenticating a TMDb user with the v4 API.
///
/// The v4 flow exchanges credentials in three steps: create a request token
/// with ``requestToken(redirectURL:)``, send the user to
/// ``authenticateURL(for:)`` to approve it in a browser, then exchange the
/// approved token for a long-lived user access token with
/// ``createAccessToken(withRequestToken:)``.
///
/// - Important: The v4 authentication endpoints authenticate with a *bearer*
/// credential, so they require a client created with
/// ``TMDbClient/init(bearerToken:configuration:)`` using your API Read Access
/// Token. A v3 API key is rejected by these endpoints. See
/// <doc:AuthenticatingWithV4> for how the v3 and v4 flows differ.
///
/// [TMDb API - Authentication (v4)](https://developer.themoviedb.org/v4/docs/authentication-user)
///
@available(macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0, *)
public protocol V4AuthenticationService: Sendable {

    ///
    /// Creates an intermediate request token that a TMDb user can approve.
    ///
    /// The returned token carries no authority of its own — it must be
    /// approved by the user at ``authenticateURL(for:)`` before it can be
    /// exchanged for an access token. Request tokens expire 15 minutes after
    /// they are issued.
    ///
    /// - Parameter redirectURL: Optional URL to redirect to once the user has
    /// approved the request token.
    ///
    /// - Throws: TMDb error ``TMDbError``.
    ///
    /// - Returns: An intermediate request token.
    ///
    func requestToken(redirectURL: URL?) async throws(TMDbError) -> V4RequestToken

    ///
    /// Builds the URL the user must visit to approve a request token.
    ///
    /// An intermediate request token can be generated by calling
    /// ``requestToken(redirectURL:)``.
    ///
    /// - Parameter requestToken: An intermediate request token.
    ///
    /// - Returns: The URL at which the user approves access.
    ///
    func authenticateURL(for requestToken: V4RequestToken) -> URL

    ///
    /// Exchanges an approved request token for a user access token.
    ///
    /// - Note: Ensure the request token has been approved by the user in a web
    /// browser, by taking them to the URL generated by
    /// ``authenticateURL(for:)``. Exchanging an unapproved token fails.
    ///
    /// - Parameter requestToken: A user-approved request token.
    ///
    /// - Throws: TMDb error ``TMDbError``.
    ///
    /// - Returns: A user access token.
    ///
    func createAccessToken(
        withRequestToken requestToken: V4RequestToken
    ) async throws(TMDbError) -> V4AccessToken

    ///
    /// Revokes a user access token.
    ///
    /// - Parameter accessToken: The access token to revoke.
    ///
    /// - Throws: TMDb error ``TMDbError``.
    ///
    /// - Returns: Whether or not the access token was successfully revoked.
    ///
    @discardableResult
    func deleteAccessToken(_ accessToken: String) async throws(TMDbError) -> Bool

}

@available(macOS 13.0, iOS 16.0, watchOS 9.0, tvOS 16.0, *)
public extension V4AuthenticationService {

    ///
    /// Creates an intermediate request token that a TMDb user can approve,
    /// with no redirect.
    ///
    /// The returned token carries no authority of its own — it must be
    /// approved by the user at ``authenticateURL(for:)`` before it can be
    /// exchanged for an access token. Request tokens expire 15 minutes after
    /// they are issued.
    ///
    /// - Throws: TMDb error ``TMDbError``.
    ///
    /// - Returns: An intermediate request token.
    ///
    /// - Note: This convenience deliberately takes no parameters rather than
    /// defaulting `redirectURL` to `nil`. A default argument is not part of a
    /// function's signature for witness matching, so a defaulted overload here
    /// would *become* the requirement's default implementation — and a
    /// conforming type that omitted the method would compile, then recurse
    /// until the stack overflowed. A distinct signature makes the omission a
    /// compile error instead.
    ///
    func requestToken() async throws(TMDbError) -> V4RequestToken {
        try await requestToken(redirectURL: nil)
    }

}
