excluded:
  - .build

opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - sorted_imports

identifier_name:
  excluded:
    - all
    - api
    - day
    - id
    - job
    - key
    - lhs
    - rhs
    - tv
    - url

line_length:
  ignores_urls: true

cyclomatic_complexity:
  ignores_case_statements: true
