os:
  - osx

language: generic

osx_image: xcode11.4

branches:
  only:
  - master

addons:
  homebrew:
    packages:
    - swiftlint

jobs:
  include:
  - stage: validation
    name: "Validation"
    script:
    - set -o pipefail
    - swiftlint
  - stage: "Test"
    name: "Run Unit tests"
    script:
    - swift test

