os:
  - osx

language: generic

osx_image: xcode11.4

branches:
  only:
  - master

addons:
  homebrew:
    packages:
    - swiftlint

env:
- SWIFT_VERSION=5.2.2

script:
- set -o pipefail
- swiftlint
- swift build
- swift test
