os: osx
osx_image: xcode11.4
language: generic

branches:
  only:
  - master

addons:
  homebrew:
    packages:
    - swiftlint

env:
- SWIFT_VERSION=5.2

script:
- set -o pipefail
- swiftlint
- swift build
