#
# TMDb
# Azure Pipeline
#

name: tmdb-$(Build.BuildId)

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

variables:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app

pool:
  vmImage: macOS-latest

steps:
- script: brew reinstall swiftlint
  displayName: 'Install swiftlint'
- script: |
    set -o pipefail
    swiftlint
  displayName: 'Lint'
- task: Cache@2
  displayName: 'Restore Cache'
  inputs:
    key: 'tmdb|swift'
    path: '$(System.DefaultWorkingDirectory)/.build'
- script: swift build
  displayName: Build
- script: swift test --enable-code-coverage
  displayName: Test
