#if !canImport(ObjectiveC)
import XCTest

extension APIConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APIConfigurationTests = [
        ("testDecodeReturnsAPIConfiguration", testDecodeReturnsAPIConfiguration),
    ]
}

extension BackdropURLProvidingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BackdropURLProvidingTests = [
        ("testBackdropAspectRatioReturnsAspectRatio", testBackdropAspectRatioReturnsAspectRatio),
        ("testBackdropLargeURLReturnsNil", testBackdropLargeURLReturnsNil),
        ("testBackdropLargeURLReturnsURL", testBackdropLargeURLReturnsURL),
        ("testBackdropMediumURLReturnsNil", testBackdropMediumURLReturnsNil),
        ("testBackdropMediumURLReturnsURL", testBackdropMediumURLReturnsURL),
        ("testBackdropOriginalURLReturnsNil", testBackdropOriginalURLReturnsNil),
        ("testBackdropOriginalURLReturnsURL", testBackdropOriginalURLReturnsURL),
        ("testBackdropSmallURLReturnsNil", testBackdropSmallURLReturnsNil),
        ("testBackdropSmallURLReturnsURL", testBackdropSmallURLReturnsURL),
    ]
}

extension CastMemberTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CastMemberTests = [
        ("testDecodeReturnsCastMember", testDecodeReturnsCastMember),
    ]
}

extension CertificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CertificationTests = [
        ("testDecodeReturnsCertification", testDecodeReturnsCertification),
        ("testIDReturnsCode", testIDReturnsCode),
    ]
}

extension CertificationsDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CertificationsDTOTests = [
        ("testDecodeReturnsCertifications", testDecodeReturnsCertifications),
    ]
}

extension CertificationsEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CertificationsEndpointTests = [
        ("testMovieEndpointReturnsURL", testMovieEndpointReturnsURL),
        ("testTVShowEndpointReturnsURL", testTVShowEndpointReturnsURL),
    ]
}

extension ConfigurationEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConfigurationEndpointTests = [
        ("testAPIEndpointReturnsURL", testAPIEndpointReturnsURL),
    ]
}

extension CrewMemberTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CrewMemberTests = [
        ("testDecodeReturnsCrewMember", testDecodeReturnsCrewMember),
    ]
}

extension DataFormatterTMDbTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DataFormatterTMDbTests = [
        ("testTheMovieDatabaseFormatterHasCorrectDateFormat", testTheMovieDatabaseFormatterHasCorrectDateFormat),
    ]
}

extension DiscoverEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DiscoverEndpointTests = [
        ("testMoviesEndpointReturnsURL", testMoviesEndpointReturnsURL),
        ("testMoviesEndpointWithPageReturnsURL", testMoviesEndpointWithPageReturnsURL),
        ("testMoviesEndpointWithSortedByAndWithPeopleAndPageReturnsURL", testMoviesEndpointWithSortedByAndWithPeopleAndPageReturnsURL),
        ("testMoviesEndpointWithSortedByReturnsURL", testMoviesEndpointWithSortedByReturnsURL),
        ("testMoviesEndpointWithWithPeopleReturnsURL", testMoviesEndpointWithWithPeopleReturnsURL),
        ("testTVShowsEndpointReturnsURL", testTVShowsEndpointReturnsURL),
        ("testTVShowsEndpointWithPageReturnsURL", testTVShowsEndpointWithPageReturnsURL),
        ("testTVShowsEndpointWithSortedByAndPageReturnsURL", testTVShowsEndpointWithSortedByAndPageReturnsURL),
        ("testTVShowsEndpointWithSortedByReturnsURL", testTVShowsEndpointWithSortedByReturnsURL),
    ]
}

extension GenderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GenderTests = [
        ("testFemaleGenderReturnsRawValue", testFemaleGenderReturnsRawValue),
        ("testMaleGenderReturnsRawValue", testMaleGenderReturnsRawValue),
        ("testOtherGenderReturnsRawValue", testOtherGenderReturnsRawValue),
        ("testUnknownGenderReturnsRawValue", testUnknownGenderReturnsRawValue),
    ]
}

extension GenreTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GenreTests = [
        ("testDecodeReturnsGenre", testDecodeReturnsGenre),
    ]
}

extension ImageCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageCollectionTests = [
        ("testDecodeReturnsImageCollection", testDecodeReturnsImageCollection),
    ]
}

extension ImageMetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImageMetadataTests = [
        ("testDecodeReturnsImageMetadata", testDecodeReturnsImageMetadata),
        ("testIDReturnsFilePath", testIDReturnsFilePath),
    ]
}

extension ImagesConfigurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ImagesConfigurationTests = [
        ("testDecodeReturnsImagesConfiguration", testDecodeReturnsImagesConfiguration),
    ]
}

extension JSONDecoderTMDbTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONDecoderTMDbTests = [
        ("testTheMovieDatabaseDecoderDecodesObject", testTheMovieDatabaseDecoderDecodesObject),
    ]
}

extension LogoURLProvidingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LogoURLProvidingTests = [
        ("testLogoLargeURLReturnsNil", testLogoLargeURLReturnsNil),
        ("testLogoLargeURLReturnsURL", testLogoLargeURLReturnsURL),
        ("testLogoMediumURLReturnsNil", testLogoMediumURLReturnsNil),
        ("testLogoMediumURLReturnsURL", testLogoMediumURLReturnsURL),
        ("testLogoOriginalURLReturnsNil", testLogoOriginalURLReturnsNil),
        ("testLogoOriginalURLReturnsURL", testLogoOriginalURLReturnsURL),
        ("testLogoSmallURLReturnsNil", testLogoSmallURLReturnsNil),
        ("testLogoSmallURLReturnsURL", testLogoSmallURLReturnsURL),
    ]
}

extension MediaPageableListDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MediaPageableListDTOTests = [
        ("testDecodeReturnsMediaPageableList", testDecodeReturnsMediaPageableList),
    ]
}

extension MediaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MediaTests = [
        ("testDecodeReturnsMedias", testDecodeReturnsMedias),
        ("testIDWhenMovieReturnsID", testIDWhenMovieReturnsID),
        ("testIDWhenPersonReturnsID", testIDWhenPersonReturnsID),
        ("testIDWhenTVShowReturnsID", testIDWhenTVShowReturnsID),
    ]
}

extension MoviePageableListDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MoviePageableListDTOTests = [
        ("testDecodeReturnsMoviePageableList", testDecodeReturnsMoviePageableList),
    ]
}

extension MovieSortByTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MovieSortByTests = [
        ("testDefaultReturnsRawValue", testDefaultReturnsRawValue),
        ("testOriginalTitleAscendingReturnsRawValue", testOriginalTitleAscendingReturnsRawValue),
        ("testOriginalTitleDescendingReturnsRawValue", testOriginalTitleDescendingReturnsRawValue),
        ("testPopularityAscendingReturnsRawValue", testPopularityAscendingReturnsRawValue),
        ("testPopularityDescendingReturnsRawValue", testPopularityDescendingReturnsRawValue),
        ("testPrimaryReleaseDateAscendingAscendingReturnsRawValue", testPrimaryReleaseDateAscendingAscendingReturnsRawValue),
        ("testPrimaryReleaseDateDescendingDescendingReturnsRawValue", testPrimaryReleaseDateDescendingDescendingReturnsRawValue),
        ("testReleaseDateAscendingReturnsRawValue", testReleaseDateAscendingReturnsRawValue),
        ("testReleaseDateDescendingReturnsRawValue", testReleaseDateDescendingReturnsRawValue),
        ("testRevenueAscendingReturnsRawValue", testRevenueAscendingReturnsRawValue),
        ("testRevenueDescendingReturnsRawValue", testRevenueDescendingReturnsRawValue),
        ("testURLAppendingNilSortByReturnsURL", testURLAppendingNilSortByReturnsURL),
        ("testURLAppendingSortByReturnsURL", testURLAppendingSortByReturnsURL),
        ("testVoteAverageAscendingReturnsRawValue", testVoteAverageAscendingReturnsRawValue),
        ("testVoteAverageDescendingReturnsRawValue", testVoteAverageDescendingReturnsRawValue),
        ("testVoteCountAscendingReturnsRawValue", testVoteCountAscendingReturnsRawValue),
        ("testVoteCountDescendingReturnsRawValue", testVoteCountDescendingReturnsRawValue),
    ]
}

extension MovieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MovieTests = [
        ("testDecodeReturnsMovie", testDecodeReturnsMovie),
        ("testHomepageURLWhenHasURLReturnsURL", testHomepageURLWhenHasURLReturnsURL),
        ("testHomepageURLWhenNilReturnsNil", testHomepageURLWhenNilReturnsNil),
        ("testReleaseDateWhenNilReturnsNil", testReleaseDateWhenNilReturnsNil),
    ]
}

extension MoviesEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MoviesEndpointTests = [
        ("testMovieCreditsEndpointReturnsURL", testMovieCreditsEndpointReturnsURL),
        ("testMovieDetailsEndpointReturnsURL", testMovieDetailsEndpointReturnsURL),
        ("testMovieImagesEndpointReturnsURL", testMovieImagesEndpointReturnsURL),
        ("testMoviePopularEndpointReturnsURL", testMoviePopularEndpointReturnsURL),
        ("testMoviePopularEndpointWithPageReturnsURL", testMoviePopularEndpointWithPageReturnsURL),
        ("testMovieRecommendationsEndpointReturnsURL", testMovieRecommendationsEndpointReturnsURL),
        ("testMovieRecommendationsEndpointWithPageReturnsURL", testMovieRecommendationsEndpointWithPageReturnsURL),
        ("testMovieReviewsEndpointReturnsURL", testMovieReviewsEndpointReturnsURL),
        ("testMovieReviewsEndpointWithPageReturnsURL", testMovieReviewsEndpointWithPageReturnsURL),
        ("testMovieSimilarEndpointReturnsURL", testMovieSimilarEndpointReturnsURL),
        ("testMovieSimilarEndpointWithPageReturnsURL", testMovieSimilarEndpointWithPageReturnsURL),
        ("testMovieVideosEndpointReturnsURL", testMovieVideosEndpointReturnsURL),
    ]
}

extension NetworkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NetworkTests = [
        ("testDecodeReturnsNetwork", testDecodeReturnsNetwork),
    ]
}

extension PageableListResultTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PageableListResultTests = [
        ("testDecodeReturnsPageableListResult", testDecodeReturnsPageableListResult),
    ]
}

extension PeopleEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PeopleEndpointTests = [
        ("testPersonCombinedCreditsEndpointReturnsURL", testPersonCombinedCreditsEndpointReturnsURL),
        ("testPersonDetailsEndpointReturnsURL", testPersonDetailsEndpointReturnsURL),
        ("testPersonImagesEndpointReturnsURL", testPersonImagesEndpointReturnsURL),
        ("testPersonMovieCreditsEndpointReturnsURL", testPersonMovieCreditsEndpointReturnsURL),
        ("testPersonTVShowCreditsEndpointReturnsURL", testPersonTVShowCreditsEndpointReturnsURL),
        ("testPopularPeopleEndpointReturnsURL", testPopularPeopleEndpointReturnsURL),
        ("testPopularPeopleEndpointWithPageReturnsURL", testPopularPeopleEndpointWithPageReturnsURL),
    ]
}

extension PersonCombinedCreditsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonCombinedCreditsTests = [
        ("testDecodeReturnsPersonCombinedCredits", testDecodeReturnsPersonCombinedCredits),
    ]
}

extension PersonImageCollectionDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonImageCollectionDTOTests = [
        ("testDecodeReturnsPersonImageCollection", testDecodeReturnsPersonImageCollection),
    ]
}

extension PersonMovieCreditsDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonMovieCreditsDTOTests = [
        ("testDecodeReturnsPersonMovieCredits", testDecodeReturnsPersonMovieCredits),
    ]
}

extension PersonPageableListDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonPageableListDTOTests = [
        ("testDecodeReturnsPersonPageableList", testDecodeReturnsPersonPageableList),
    ]
}

extension PersonTVShowCreditsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonTVShowCreditsTests = [
        ("testDecodeReturnsPersonTVShowCredits", testDecodeReturnsPersonTVShowCredits),
    ]
}

extension PersonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PersonTests = [
        ("testDecodeReturnsPerson", testDecodeReturnsPerson),
        ("testHomepageURLWhenHasURLReturnsURL", testHomepageURLWhenHasURLReturnsURL),
        ("testHomepageURLWhenNilReturnsNil", testHomepageURLWhenNilReturnsNil),
    ]
}

extension PosterURLProvidingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PosterURLProvidingTests = [
        ("testPosterAspectRatioReturnsAspectRatio", testPosterAspectRatioReturnsAspectRatio),
        ("testPosterLargeURLReturnsNil", testPosterLargeURLReturnsNil),
        ("testPosterLargeURLReturnsURL", testPosterLargeURLReturnsURL),
        ("testPosterMediumURLReturnsNil", testPosterMediumURLReturnsNil),
        ("testPosterMediumURLReturnsURL", testPosterMediumURLReturnsURL),
        ("testPosterOriginalURLReturnsNil", testPosterOriginalURLReturnsNil),
        ("testPosterOriginalURLReturnsURL", testPosterOriginalURLReturnsURL),
        ("testPosterSmallURLReturnsNil", testPosterSmallURLReturnsNil),
        ("testPosterSmallURLReturnsURL", testPosterSmallURLReturnsURL),
    ]
}

extension ProductionCompanyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductionCompanyTests = [
        ("testDecodeReturnsProductionCompany", testDecodeReturnsProductionCompany),
    ]
}

extension ProductionCountryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductionCountryTests = [
        ("testDecodeReturnsProductionCountry", testDecodeReturnsProductionCountry),
        ("testIDReturnsISO31661", testIDReturnsISO31661),
    ]
}

extension ProfileURLProvidingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProfileURLProvidingTests = [
        ("testProfileAspectRatioReturnsAspectRatio", testProfileAspectRatioReturnsAspectRatio),
        ("testProfileLargeURLReturnsNil", testProfileLargeURLReturnsNil),
        ("testProfileLargeURLReturnsURL", testProfileLargeURLReturnsURL),
        ("testProfileMediumURLReturnsNil", testProfileMediumURLReturnsNil),
        ("testProfileMediumURLReturnsURL", testProfileMediumURLReturnsURL),
        ("testProfileOriginalURLReturnsNil", testProfileOriginalURLReturnsNil),
        ("testProfileOriginalURLReturnsURL", testProfileOriginalURLReturnsURL),
        ("testProfileSmallURLReturnsNil", testProfileSmallURLReturnsNil),
        ("testProfileSmallURLReturnsURL", testProfileSmallURLReturnsURL),
    ]
}

extension ReviewPageableListDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReviewPageableListDTOTests = [
        ("testDecodeReturnsReviewPageableList", testDecodeReturnsReviewPageableList),
    ]
}

extension ReviewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReviewTests = [
        ("testDecodeReturnsReview", testDecodeReturnsReview),
    ]
}

extension SearchEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SearchEndpointTests = [
        ("testMoviesSearchEndpointReturnsURL", testMoviesSearchEndpointReturnsURL),
        ("testMoviesSearchEndpointWithPageReturnsURL", testMoviesSearchEndpointWithPageReturnsURL),
        ("testMoviesSearchEndpointWithYearAndPageReturnsURL", testMoviesSearchEndpointWithYearAndPageReturnsURL),
        ("testMoviesSearchEndpointWithYearReturnsURL", testMoviesSearchEndpointWithYearReturnsURL),
        ("testMultiSearchEndpointReturnsURL", testMultiSearchEndpointReturnsURL),
        ("testMultiSearchEndpointWithPageReturnsURL", testMultiSearchEndpointWithPageReturnsURL),
        ("testPeopleSearchEndpointReturnsURL", testPeopleSearchEndpointReturnsURL),
        ("testPeopleSearchEndpointWithPageReturnsURL", testPeopleSearchEndpointWithPageReturnsURL),
        ("testTVShowsSearchEndpointReturnsURL", testTVShowsSearchEndpointReturnsURL),
        ("testTVShowsSearchEndpointWithFirstAirDateYearReturnsURL", testTVShowsSearchEndpointWithFirstAirDateYearReturnsURL),
        ("testTVShowsSearchEndpointWithPageReturnsURL", testTVShowsSearchEndpointWithPageReturnsURL),
        ("testTVShowsSearchEndpointWithYearAndPageReturnsURL", testTVShowsSearchEndpointWithYearAndPageReturnsURL),
    ]
}

extension ShowCreditsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShowCreditsTests = [
        ("testDecodeReturnsShowCredits", testDecodeReturnsShowCredits),
    ]
}

extension ShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ShowTests = [
        ("testDateWhenMovieReturnsMovieReleaseDate", testDateWhenMovieReturnsMovieReleaseDate),
        ("testDateWhenTVShowReturnsTVShowFirstAirDate", testDateWhenTVShowReturnsTVShowFirstAirDate),
        ("testDecodeReturnsMovie", testDecodeReturnsMovie),
        ("testDecodeReturnsTVShow", testDecodeReturnsTVShow),
        ("testIDWhenMovieReturnsMovieID", testIDWhenMovieReturnsMovieID),
        ("testIDWhenTVShowReturnsTVShowID", testIDWhenTVShowReturnsTVShowID),
        ("testPopularityWhenMovieReturnsMoviePopularity", testPopularityWhenMovieReturnsMoviePopularity),
        ("testPopularityWhenTVShowReturnsTVShowPopularity", testPopularityWhenTVShowReturnsTVShowPopularity),
    ]
}

extension SpokenLanguageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SpokenLanguageTests = [
        ("testDecodeReturnsSpokenLanguage", testDecodeReturnsSpokenLanguage),
        ("testIDReturnsISO6391", testIDReturnsISO6391),
    ]
}

extension StatusTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StatusTests = [
        ("testCanceledStatusReturnsRawValue", testCanceledStatusReturnsRawValue),
        ("testInProductionStatusReturnsRawValue", testInProductionStatusReturnsRawValue),
        ("testPlannedStatusReturnsRawValue", testPlannedStatusReturnsRawValue),
        ("testPostProductionStatusReturnsRawValue", testPostProductionStatusReturnsRawValue),
        ("testReleasedStatusReturnsRawValue", testReleasedStatusReturnsRawValue),
        ("testRumoredStatusReturnsRawValue", testRumoredStatusReturnsRawValue),
    ]
}

extension StillURLProvidingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StillURLProvidingTests = [
        ("testStillAspectRatioReturnsAspectRatio", testStillAspectRatioReturnsAspectRatio),
        ("testStillLargeURLReturnsNil", testStillLargeURLReturnsNil),
        ("testStillLargeURLReturnsURL", testStillLargeURLReturnsURL),
        ("testStillMediumURLReturnsNil", testStillMediumURLReturnsNil),
        ("testStillMediumURLReturnsURL", testStillMediumURLReturnsURL),
        ("testStillOriginalURLReturnsNil", testStillOriginalURLReturnsNil),
        ("testStillOriginalURLReturnsURL", testStillOriginalURLReturnsURL),
        ("testStillSmallURLReturnsNil", testStillSmallURLReturnsNil),
        ("testStillSmallURLReturnsURL", testStillSmallURLReturnsURL),
    ]
}

extension TMDbAPIAPIKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIAPIKeyTests = [
        ("testSetAPIKeySetsAPIKeyOnAPIClient", testSetAPIKeySetsAPIKeyOnAPIClient),
    ]
}

extension TMDbAPICertificationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPICertificationTests = [
        ("testMovieCertificationsPublisherReturnsCertifications", testMovieCertificationsPublisherReturnsCertifications),
        ("testTVShowCertificationsPublisherReturnsCertifications", testTVShowCertificationsPublisherReturnsCertifications),
    ]
}

extension TMDbAPIClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIClientTests = [
        ("testSetAPIKey", testSetAPIKey),
        ("testStaticSetAPIKey", testStaticSetAPIKey),
    ]
}

extension TMDbAPIConifgurationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIConifgurationTests = [
        ("testAPIConfigurationPublisherReturnsAPIConfiguration", testAPIConfigurationPublisherReturnsAPIConfiguration),
    ]
}

extension TMDbAPIDiscoverTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIDiscoverTests = [
        ("testDiscoverMoviesPublisherReturnsMovies", testDiscoverMoviesPublisherReturnsMovies),
        ("testDiscoverMoviesPublisherWithPageReturnsMovies", testDiscoverMoviesPublisherWithPageReturnsMovies),
        ("testDiscoverMoviesPublisherWithPeopleReturnsMovies", testDiscoverMoviesPublisherWithPeopleReturnsMovies),
        ("testDiscoverMoviesPublisherWithSortByReturnsMovies", testDiscoverMoviesPublisherWithSortByReturnsMovies),
        ("testDiscoverMoviesPublisherWithSortByWithPeoplePageReturnsMovies", testDiscoverMoviesPublisherWithSortByWithPeoplePageReturnsMovies),
        ("testDiscoverTVShowsPublisherReturnsTVShows", testDiscoverTVShowsPublisherReturnsTVShows),
        ("testDiscoverTVShowsPublisherWithPageReturnsTVShows", testDiscoverTVShowsPublisherWithPageReturnsTVShows),
        ("testDiscoverTVShowsPublisherWithSortByPageReturnsTVShows", testDiscoverTVShowsPublisherWithSortByPageReturnsTVShows),
        ("testDiscoverTVShowsPublisherWithSortByReturnsTVShows", testDiscoverTVShowsPublisherWithSortByReturnsTVShows),
    ]
}

extension TMDbAPIMovieTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIMovieTests = [
        ("testCreditsPublisherForMovieReturnsShowCredits", testCreditsPublisherForMovieReturnsShowCredits),
        ("testDetailsPublisherForMovieReturnsMovie", testDetailsPublisherForMovieReturnsMovie),
        ("testImagesPublisherForMovieReturnsImages", testImagesPublisherForMovieReturnsImages),
        ("testMoviesPublisherSimilarToMovieReturnsMovies", testMoviesPublisherSimilarToMovieReturnsMovies),
        ("testMoviesPublisherSimilarToMovieWithPageReturnsMovies", testMoviesPublisherSimilarToMovieWithPageReturnsMovies),
        ("testPopularMoviesPublisherReturnsMovies", testPopularMoviesPublisherReturnsMovies),
        ("testPopularMoviesPublisherWithPageReturnsMovies", testPopularMoviesPublisherWithPageReturnsMovies),
        ("testRecommendationsPublisherForMovieReturnsMovies", testRecommendationsPublisherForMovieReturnsMovies),
        ("testRecommendationsPublisherForMovieWithPageReturnsMovies", testRecommendationsPublisherForMovieWithPageReturnsMovies),
        ("testReviewsPublisherForMovieReturnsReviews", testReviewsPublisherForMovieReturnsReviews),
        ("testVideosPublisherForMovieReturnsVideos", testVideosPublisherForMovieReturnsVideos),
    ]
}

extension TMDbAPIPeopleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPIPeopleTests = [
        ("testCombinedCreditsPublisherForPersonReturnsCombinedCredits", testCombinedCreditsPublisherForPersonReturnsCombinedCredits),
        ("testDetailsPublisherForPersonReturnsPerson", testDetailsPublisherForPersonReturnsPerson),
        ("testImagesPublisherForPersonReturnsImages", testImagesPublisherForPersonReturnsImages),
        ("testKnowForPublisherForPersonReturnsShows", testKnowForPublisherForPersonReturnsShows),
        ("testMovieCreditsPublisherForPersonReturnsMovieCredits", testMovieCreditsPublisherForPersonReturnsMovieCredits),
        ("testPopularPeoplePublisherReturnsPeople", testPopularPeoplePublisherReturnsPeople),
        ("testPopularPeoplePublisherWithPageReturnsPeople", testPopularPeoplePublisherWithPageReturnsPeople),
        ("testTVShowCreditsPublisherForPersonReturnsTVShowCredits", testTVShowCreditsPublisherForPersonReturnsTVShowCredits),
    ]
}

extension TMDbAPISearchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPISearchTests = [
        ("testSearchMoviesPublisherReturnsMovies", testSearchMoviesPublisherReturnsMovies),
        ("testSearchMoviesPublisherWithPageReturnsMovies", testSearchMoviesPublisherWithPageReturnsMovies),
        ("testSearchMoviesPublisherWithYearPageReturnsMovies", testSearchMoviesPublisherWithYearPageReturnsMovies),
        ("testSearchMoviesPublisherWithYearReturnsMovies", testSearchMoviesPublisherWithYearReturnsMovies),
        ("testSearchPeoplePublisherReturnsPeople", testSearchPeoplePublisherReturnsPeople),
        ("testSearchPeoplePublisherWithPageReturnsPeople", testSearchPeoplePublisherWithPageReturnsPeople),
        ("testSearchPublisherReturnsMedia", testSearchPublisherReturnsMedia),
        ("testSearchPublisherWithPageReturnsMedia", testSearchPublisherWithPageReturnsMedia),
        ("testSearchTVShowsPublisherReturnsTVShows", testSearchTVShowsPublisherReturnsTVShows),
        ("testSearchTVShowsPublisherWithFirstAirDateYearPageReturnsTVShows", testSearchTVShowsPublisherWithFirstAirDateYearPageReturnsTVShows),
        ("testSearchTVShowsPublisherWithFirstAirDateYearReturnsTVShows", testSearchTVShowsPublisherWithFirstAirDateYearReturnsTVShows),
        ("testSearchTVShowsPublisherWithPageReturnsTVShows", testSearchTVShowsPublisherWithPageReturnsTVShows),
    ]
}

extension TMDbAPITVShowSeasonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPITVShowSeasonTests = [
        ("testDetailsPublisherForTVShowSeasonReturnsTVShowSeason", testDetailsPublisherForTVShowSeasonReturnsTVShowSeason),
        ("testImagesPublisherForTVShowSeasonReturnsImages", testImagesPublisherForTVShowSeasonReturnsImages),
        ("testVideosPublisherForTVShowSeasonReturnsImages", testVideosPublisherForTVShowSeasonReturnsImages),
    ]
}

extension TMDbAPITVShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPITVShowTests = [
        ("testCreditsPublisherForTVShowReturnsShowCredits", testCreditsPublisherForTVShowReturnsShowCredits),
        ("testDetailsPublisherForTVShowReturnsTVShow", testDetailsPublisherForTVShowReturnsTVShow),
        ("testImagesPublisherForTVShowReturnsImages", testImagesPublisherForTVShowReturnsImages),
        ("testPopularTVShowsPublisherReturnsTVShows", testPopularTVShowsPublisherReturnsTVShows),
        ("testPopularTVShowsPublisherWithPageReturnsTVShows", testPopularTVShowsPublisherWithPageReturnsTVShows),
        ("testRecommendationsPublisherForTVShowReturnsTVShows", testRecommendationsPublisherForTVShowReturnsTVShows),
        ("testRecommendationsPublisherForTVShowWithPageReturnsTVShows", testRecommendationsPublisherForTVShowWithPageReturnsTVShows),
        ("testReviewsPublisherForTVShowReturnsReviews", testReviewsPublisherForTVShowReturnsReviews),
        ("testTVShowsPublisherSimilarToTVShowReturnsTVShows", testTVShowsPublisherSimilarToTVShowReturnsTVShows),
        ("testTVShowsPublisherSimilarToTVShowWithPageReturnsTVShows", testTVShowsPublisherSimilarToTVShowWithPageReturnsTVShows),
        ("testVideosPublisherForTVShowReturnsVideos", testVideosPublisherForTVShowReturnsVideos),
    ]
}

extension TMDbAPITrendingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbAPITrendingTests = [
        ("testTrendingMoviesPublisherReturnsMovies", testTrendingMoviesPublisherReturnsMovies),
        ("testTrendingMoviesPublisherWithPageReturnsMovies", testTrendingMoviesPublisherWithPageReturnsMovies),
        ("testTrendingMoviesPublisherWithTimeWindowPageReturnsMovies", testTrendingMoviesPublisherWithTimeWindowPageReturnsMovies),
        ("testTrendingMoviesPublisherWithTimeWindowReturnsMovies", testTrendingMoviesPublisherWithTimeWindowReturnsMovies),
        ("testTrendingPeoplePublisherReturnsPeople", testTrendingPeoplePublisherReturnsPeople),
        ("testTrendingPeoplePublisherWithPageReturnsPeople", testTrendingPeoplePublisherWithPageReturnsPeople),
        ("testTrendingPeoplePublisherWithTimeWindowPageReturnsPeople", testTrendingPeoplePublisherWithTimeWindowPageReturnsPeople),
        ("testTrendingPeoplePublisherWithTimeWindowReturnsPeople", testTrendingPeoplePublisherWithTimeWindowReturnsPeople),
        ("testTrendingTVShowsPublisherReturnsTVShows", testTrendingTVShowsPublisherReturnsTVShows),
        ("testTrendingTVShowsPublisherWithPageReturnsTVShows", testTrendingTVShowsPublisherWithPageReturnsTVShows),
        ("testTrendingTVShowsPublisherWithTimeWindowPageReturnsTVShows", testTrendingTVShowsPublisherWithTimeWindowPageReturnsTVShows),
        ("testTrendingTVShowsPublisherWithTimeWindowReturnsTVShows", testTrendingTVShowsPublisherWithTimeWindowReturnsTVShows),
    ]
}

extension TMDbCertificationServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbCertificationServiceTests = [
        ("testFetchMovieCertificationsReturnsMovieCertifications", testFetchMovieCertificationsReturnsMovieCertifications),
        ("testFetchTVShowCertificationsReturnsMovieCertifications", testFetchTVShowCertificationsReturnsMovieCertifications),
    ]
}

extension TMDbConfigurationServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbConfigurationServiceTests = [
        ("testFetchAPIConfigurationReturnsAPIConfiguration", testFetchAPIConfigurationReturnsAPIConfiguration),
    ]
}

extension TMDbDiscoverServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbDiscoverServiceTests = [
        ("testFetchMoviesReturnsMovies", testFetchMoviesReturnsMovies),
        ("testFetchMoviesWithSortByAndWithPeopleAndPageReturnsMovies", testFetchMoviesWithSortByAndWithPeopleAndPageReturnsMovies),
        ("testFetchMoviesWithSortByReturnsMovies", testFetchMoviesWithSortByReturnsMovies),
        ("testFetchMoviesWithWithPageReturnsMovies", testFetchMoviesWithWithPageReturnsMovies),
        ("testFetchMoviesWithWithPeopleReturnsMovies", testFetchMoviesWithWithPeopleReturnsMovies),
        ("testFetchTVShowsReturnsTVShows", testFetchTVShowsReturnsTVShows),
        ("testFetchTVShowsWithPageReturnsTVShows", testFetchTVShowsWithPageReturnsTVShows),
        ("testFetchTVShowsWithSortByAndPageReturnsTVShows", testFetchTVShowsWithSortByAndPageReturnsTVShows),
        ("testFetchTVShowsWithSortByReturnsTVShows", testFetchTVShowsWithSortByReturnsTVShows),
    ]
}

extension TMDbErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbErrorTests = [
        ("testDecodeReturnsErrorDescription", testDecodeReturnsErrorDescription),
        ("testNetworkReturnsErrorDescription", testNetworkReturnsErrorDescription),
        ("testNotFoundReturnsErrorDescription", testNotFoundReturnsErrorDescription),
        ("testUnauthorizedReturnsErrorDescription", testUnauthorizedReturnsErrorDescription),
        ("testUnknownReturnsErrorDescription", testUnknownReturnsErrorDescription),
    ]
}

extension TMDbMovieServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbMovieServiceTests = [
        ("testFetchCreditsReturnsCredits", testFetchCreditsReturnsCredits),
        ("testFetchDetailsReturnsMovie", testFetchDetailsReturnsMovie),
        ("testFetchImagesReturnsImageCollection", testFetchImagesReturnsImageCollection),
        ("testFetchPopularReturnsMovies", testFetchPopularReturnsMovies),
        ("testFetchPopularWithPageReturnsMovies", testFetchPopularWithPageReturnsMovies),
        ("testFetchRecommendationsReturnsMovies", testFetchRecommendationsReturnsMovies),
        ("testFetchRecommendationsWithPageReturnsMovies", testFetchRecommendationsWithPageReturnsMovies),
        ("testFetchReviewsReturnsReviews", testFetchReviewsReturnsReviews),
        ("testFetchReviewsWithPageReturnsReviews", testFetchReviewsWithPageReturnsReviews),
        ("testFetchSimilarReturnsMovies", testFetchSimilarReturnsMovies),
        ("testFetchSimilarWithPageReturnsMovies", testFetchSimilarWithPageReturnsMovies),
        ("testFetchVideosReturnsVideoCollection", testFetchVideosReturnsVideoCollection),
    ]
}

extension TMDbPersonServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbPersonServiceTests = [
        ("testFetchCombinedCreditsReturnsCombinedCredits", testFetchCombinedCreditsReturnsCombinedCredits),
        ("testFetchDetailsReturnsPerson", testFetchDetailsReturnsPerson),
        ("testFetchImagesReturnsImageCollection", testFetchImagesReturnsImageCollection),
        ("testFetchMovieCreditsReturnsMovieCredits", testFetchMovieCreditsReturnsMovieCredits),
        ("testFetchPopularReturnsPeople", testFetchPopularReturnsPeople),
        ("testFetchPopularWithPageReturnsPeople", testFetchPopularWithPageReturnsPeople),
        ("testFetchTVShowCreditsReturnsTVShowCredits", testFetchTVShowCreditsReturnsTVShowCredits),
    ]
}

extension TMDbSearchServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbSearchServiceTests = [
        ("testSearchAllReturnsMedia", testSearchAllReturnsMedia),
        ("testSearchAllWithPageReturnsMedia", testSearchAllWithPageReturnsMedia),
        ("testSearchMoviesReturnsMovies", testSearchMoviesReturnsMovies),
        ("testSearchMoviesWithPageReturnsMovies", testSearchMoviesWithPageReturnsMovies),
        ("testSearchMoviesWithYearAndPageReturnsMovies", testSearchMoviesWithYearAndPageReturnsMovies),
        ("testSearchMoviesWithYearReturnsMovies", testSearchMoviesWithYearReturnsMovies),
        ("testSearchPeopleReturnsPeople", testSearchPeopleReturnsPeople),
        ("testSearchPeopleWithPageReturnsPeople", testSearchPeopleWithPageReturnsPeople),
        ("testSearchTVShowsReturnsTVShows", testSearchTVShowsReturnsTVShows),
        ("testSearchTVShowsWithFirstAirDateYearANdPageReturnsTVShows", testSearchTVShowsWithFirstAirDateYearANdPageReturnsTVShows),
        ("testSearchTVShowsWithFirstAirDateYearReturnsTVShows", testSearchTVShowsWithFirstAirDateYearReturnsTVShows),
        ("testSearchTVShowsWithPageReturnsTVShows", testSearchTVShowsWithPageReturnsTVShows),
    ]
}

extension TMDbTVShowSeasonServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbTVShowSeasonServiceTests = [
        ("testFetchDetailsReturnsTVShowSeason", testFetchDetailsReturnsTVShowSeason),
        ("testFetchImagesReturnsImages", testFetchImagesReturnsImages),
        ("testFetchVideosReturnsVideos", testFetchVideosReturnsVideos),
    ]
}

extension TMDbTVShowServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbTVShowServiceTests = [
        ("testFetchCreditsReturnsShowsCredits", testFetchCreditsReturnsShowsCredits),
        ("testFetchDetailsReturnsTVShow", testFetchDetailsReturnsTVShow),
        ("testFetchImagesReturnsImages", testFetchImagesReturnsImages),
        ("testFetchPopularReturnsTVShows", testFetchPopularReturnsTVShows),
        ("testFetchPopularWithPageReturnsTVShows", testFetchPopularWithPageReturnsTVShows),
        ("testFetchRecommendationsReturnsTVShows", testFetchRecommendationsReturnsTVShows),
        ("testFetchRecommendationsWithPageReturnsTVShows", testFetchRecommendationsWithPageReturnsTVShows),
        ("testFetchReviewsReturnsReviews", testFetchReviewsReturnsReviews),
        ("testFetchReviewsWithPageReturnsReviews", testFetchReviewsWithPageReturnsReviews),
        ("testFetchSimilarReturnsTVShows", testFetchSimilarReturnsTVShows),
        ("testFetchSimilarWithPageReturnsTVShows", testFetchSimilarWithPageReturnsTVShows),
        ("testFetchVideosReturnsVideos", testFetchVideosReturnsVideos),
    ]
}

extension TMDbTrendingServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TMDbTrendingServiceTests = [
        ("testFetchMoviesForDayReturnsMovies", testFetchMoviesForDayReturnsMovies),
        ("testFetchMoviesForDayWithPageReturnsMovies", testFetchMoviesForDayWithPageReturnsMovies),
        ("testFetchMoviesForWeekReturnsMovies", testFetchMoviesForWeekReturnsMovies),
        ("testFetchMoviesForWeekWithPageReturnsMovies", testFetchMoviesForWeekWithPageReturnsMovies),
        ("testFetchPeopleForDayReturnsPeople", testFetchPeopleForDayReturnsPeople),
        ("testFetchPeopleForWeekReturnsPeople", testFetchPeopleForWeekReturnsPeople),
        ("testFetchTVShowsForDayReturnsTVShows", testFetchTVShowsForDayReturnsTVShows),
        ("testFetchTVShowsForDayWithPageReturnsPeople", testFetchTVShowsForDayWithPageReturnsPeople),
        ("testFetchTVShowsForDayWithPageReturnsTVShows", testFetchTVShowsForDayWithPageReturnsTVShows),
        ("testFetchTVShowsForWeekReturnsTVShows", testFetchTVShowsForWeekReturnsTVShows),
        ("testFetchTVShowsForWeekWithPageReturnsPeople", testFetchTVShowsForWeekWithPageReturnsPeople),
        ("testFetchTVShowsForWeekWithPageReturnsTVShows", testFetchTVShowsForWeekWithPageReturnsTVShows),
    ]
}

extension TVShowEpisodeDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowEpisodeDTOTests = [
        ("testDecodeReturnsTVShowEpisode", testDecodeReturnsTVShowEpisode),
    ]
}

extension TVShowPageableListDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowPageableListDTOTests = [
        ("testDecodeReturnsTVShowPageableList", testDecodeReturnsTVShowPageableList),
    ]
}

extension TVShowSeaonsEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowSeaonsEndpointTests = [
        ("testTVShowSeasonDetailsEndpointReturnsURL", testTVShowSeasonDetailsEndpointReturnsURL),
        ("testTVShowSeasonImagesEndpointReturnsURL", testTVShowSeasonImagesEndpointReturnsURL),
        ("testTVShowSeasonVideosEndpointReturnsURL", testTVShowSeasonVideosEndpointReturnsURL),
    ]
}

extension TVShowSeasonDTOTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowSeasonDTOTests = [
        ("testDecodeReturnsTVShowSeason", testDecodeReturnsTVShowSeason),
    ]
}

extension TVShowSortByTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowSortByTests = [
        ("testDefaultReturnsRawValue", testDefaultReturnsRawValue),
        ("testFirstAirDateAscendingReturnsRawValue", testFirstAirDateAscendingReturnsRawValue),
        ("testFirstAirDateDescendingReturnsRawValue", testFirstAirDateDescendingReturnsRawValue),
        ("testPopularityAscendingReturnsRawValue", testPopularityAscendingReturnsRawValue),
        ("testPopularityDescendingReturnsRawValue", testPopularityDescendingReturnsRawValue),
        ("testURLAppendingNilSortByReturnsURL", testURLAppendingNilSortByReturnsURL),
        ("testURLAppendingSortByReturnsURL", testURLAppendingSortByReturnsURL),
        ("testVoteAverageAscendingReturnsRawValue", testVoteAverageAscendingReturnsRawValue),
        ("testVoteAverageDescendingReturnsRawValue", testVoteAverageDescendingReturnsRawValue),
    ]
}

extension TVShowTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowTests = [
        ("testDecodeReturnsTVShow", testDecodeReturnsTVShow),
        ("testFirstAirDateWhenNilReturnsNil", testFirstAirDateWhenNilReturnsNil),
        ("testHomepageURLWhenHasURLReturnsURL", testHomepageURLWhenHasURLReturnsURL),
        ("testHomepageURLWhenNilReturnsNil", testHomepageURLWhenNilReturnsNil),
    ]
}

extension TVShowsEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TVShowsEndpointTests = [
        ("testTVShowCreditsEndpointReturnsURL", testTVShowCreditsEndpointReturnsURL),
        ("testTVShowDetailsEndpointReturnsURL", testTVShowDetailsEndpointReturnsURL),
        ("testTVShowImagesEndpointReturnsURL", testTVShowImagesEndpointReturnsURL),
        ("testTVShowPopularEndpointReturnsURL", testTVShowPopularEndpointReturnsURL),
        ("testTVShowPopularEndpointWithPageReturnsURL", testTVShowPopularEndpointWithPageReturnsURL),
        ("testTVShowRecommendationsEndpointReturnsURL", testTVShowRecommendationsEndpointReturnsURL),
        ("testTVShowRecommendationsEndpointWithPageReturnsURL", testTVShowRecommendationsEndpointWithPageReturnsURL),
        ("testTVShowReviewsEndpointReturnsURL", testTVShowReviewsEndpointReturnsURL),
        ("testTVShowReviewsEndpointWithPageReturnsURL", testTVShowReviewsEndpointWithPageReturnsURL),
        ("testTVShowSimilarEndpointReturnsURL", testTVShowSimilarEndpointReturnsURL),
        ("testTVShowSimilarEndpointWithPageReturnsURL", testTVShowSimilarEndpointWithPageReturnsURL),
        ("testTVShowVideosEndpointReturnsURL", testTVShowVideosEndpointReturnsURL),
    ]
}

extension TrendingEndpointTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrendingEndpointTests = [
        ("testTrendingMoviesEndpointReturnsURL", testTrendingMoviesEndpointReturnsURL),
        ("testTrendingMoviesEndpointWithPageReturnsURL", testTrendingMoviesEndpointWithPageReturnsURL),
        ("testTrendingMoviesEndpointWithTimeWindowDayAndPageReturnsURL", testTrendingMoviesEndpointWithTimeWindowDayAndPageReturnsURL),
        ("testTrendingMoviesEndpointWithTimeWindowDayReturnsURL", testTrendingMoviesEndpointWithTimeWindowDayReturnsURL),
        ("testTrendingMoviesEndpointWithTimeWindowWeekAndPageReturnsURL", testTrendingMoviesEndpointWithTimeWindowWeekAndPageReturnsURL),
        ("testTrendingMoviesEndpointWithTimeWindowWeekReturnsURL", testTrendingMoviesEndpointWithTimeWindowWeekReturnsURL),
        ("testTrendingPeopleEndpointReturnsURL", testTrendingPeopleEndpointReturnsURL),
        ("testTrendingPeopleEndpointWithPageReturnsURL", testTrendingPeopleEndpointWithPageReturnsURL),
        ("testTrendingPeopleEndpointWithTimeWindowDayAndPageReturnsURL", testTrendingPeopleEndpointWithTimeWindowDayAndPageReturnsURL),
        ("testTrendingPeopleEndpointWithTimeWindowDayReturnsURL", testTrendingPeopleEndpointWithTimeWindowDayReturnsURL),
        ("testTrendingPeopleEndpointWithTimeWindowWeekAndPageReturnsURL", testTrendingPeopleEndpointWithTimeWindowWeekAndPageReturnsURL),
        ("testTrendingPeopleEndpointWithTimeWindowWeekReturnsURL", testTrendingPeopleEndpointWithTimeWindowWeekReturnsURL),
        ("testTrendingTVShowsEndpointReturnsURL", testTrendingTVShowsEndpointReturnsURL),
        ("testTrendingTVShowsEndpointWithPageReturnsURL", testTrendingTVShowsEndpointWithPageReturnsURL),
        ("testTrendingTVShowsEndpointWithTimeWindowDayAndPageReturnsURL", testTrendingTVShowsEndpointWithTimeWindowDayAndPageReturnsURL),
        ("testTrendingTVShowsEndpointWithTimeWindowDayReturnsURL", testTrendingTVShowsEndpointWithTimeWindowDayReturnsURL),
        ("testTrendingTVShowsEndpointWithTimeWindowWeekAndPageReturnsURL", testTrendingTVShowsEndpointWithTimeWindowWeekAndPageReturnsURL),
        ("testTrendingTVShowsEndpointWithTimeWindowWeekReturnsURL", testTrendingTVShowsEndpointWithTimeWindowWeekReturnsURL),
    ]
}

extension TrendingTimeWindowFilterTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrendingTimeWindowFilterTypeTests = [
        ("testDayReturnsRawValue", testDayReturnsRawValue),
        ("testDefaultReturnsRawValue", testDefaultReturnsRawValue),
        ("testWeekReturnsRawValue", testWeekReturnsRawValue),
    ]
}

extension URLQueryItemTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLQueryItemTests = [
        ("testAppendingAPIKeyWhenContainsQueryItemsReturnsURL", testAppendingAPIKeyWhenContainsQueryItemsReturnsURL),
        ("testAppendingAPIKeyWhenNoQueryItemsReturnsURL", testAppendingAPIKeyWhenNoQueryItemsReturnsURL),
        ("testAppendingFirstAirDateYearWhenContainsQueryItemAndYearIsNilReturnsURL", testAppendingFirstAirDateYearWhenContainsQueryItemAndYearIsNilReturnsURL),
        ("testAppendingFirstAirDateYearWhenContainsQueryItemAndYearIsNotNilReturnsURL", testAppendingFirstAirDateYearWhenContainsQueryItemAndYearIsNotNilReturnsURL),
        ("testAppendingFirstAirDateYearWhenNoQueryItemsAndYearIsNilReturnsURL", testAppendingFirstAirDateYearWhenNoQueryItemsAndYearIsNilReturnsURL),
        ("testAppendingFirstAirDateYearWhenNoQueryItemsAndYearIsNotNilReturnsURL", testAppendingFirstAirDateYearWhenNoQueryItemsAndYearIsNotNilReturnsURL),
        ("testAppendingIntPathComponentReturnsURL", testAppendingIntPathComponentReturnsURL),
        ("testAppendingPageWhenContainsQueryItemAndPageIsBetween1and1000ReturnsURL", testAppendingPageWhenContainsQueryItemAndPageIsBetween1and1000ReturnsURL),
        ("testAppendingPageWhenContainsQueryItemAndPageIsGreaterThan1000ReturnsURL", testAppendingPageWhenContainsQueryItemAndPageIsGreaterThan1000ReturnsURL),
        ("testAppendingPageWhenContainsQueryItemAndPageIsLessThan1ReturnsURL", testAppendingPageWhenContainsQueryItemAndPageIsLessThan1ReturnsURL),
        ("testAppendingPageWhenContainsQueryItemAndPageIsNilReturnsURL", testAppendingPageWhenContainsQueryItemAndPageIsNilReturnsURL),
        ("testAppendingPageWhenNoQueryItemsAndPageIsBetween1and1000ReturnsURL", testAppendingPageWhenNoQueryItemsAndPageIsBetween1and1000ReturnsURL),
        ("testAppendingPageWhenNoQueryItemsAndPageIsGreaterThan1000ReturnsURL", testAppendingPageWhenNoQueryItemsAndPageIsGreaterThan1000ReturnsURL),
        ("testAppendingPageWhenNoQueryItemsAndPageIsLessThan1ReturnsURL", testAppendingPageWhenNoQueryItemsAndPageIsLessThan1ReturnsURL),
        ("testAppendingPageWhenNoQueryItemsAndPageIsNilReturnsURL", testAppendingPageWhenNoQueryItemsAndPageIsNilReturnsURL),
        ("testAppendingQueryItemWhenContainsQueryItemsReturnsURL", testAppendingQueryItemWhenContainsQueryItemsReturnsURL),
        ("testAppendingQueryItemWhenNoQueryItemsReturnsURL", testAppendingQueryItemWhenNoQueryItemsReturnsURL),
        ("testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleHasOneElementReturnsURL", testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleHasOneElementReturnsURL),
        ("testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleHasTwoElementsReturnsURL", testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleHasTwoElementsReturnsURL),
        ("testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleIsNilReturnsURL", testAppendingWithPeopleWhenContainsQueryItemAndWithPeopleIsNilReturnsURL),
        ("testAppendingWithPeopleWhenNoQueryItemsAndWithPeopleHasOneElementReturnsURL", testAppendingWithPeopleWhenNoQueryItemsAndWithPeopleHasOneElementReturnsURL),
        ("testAppendingWithPeopleWhenNoQueryItemsAndWithPeopleIsNilReturnsURL", testAppendingWithPeopleWhenNoQueryItemsAndWithPeopleIsNilReturnsURL),
        ("testAppendingYearWhenContainsQueryItemAndYearIsNilReturnsURL", testAppendingYearWhenContainsQueryItemAndYearIsNilReturnsURL),
        ("testAppendingYearWhenContainsQueryItemAndYearIsNotNilReturnsURL", testAppendingYearWhenContainsQueryItemAndYearIsNotNilReturnsURL),
        ("testAppendingYearWhenNoQueryItemsAndYearIsNilReturnsURL", testAppendingYearWhenNoQueryItemsAndYearIsNilReturnsURL),
        ("testAppendingYearWhenNoQueryItemsAndYearIsNotNilReturnsURL", testAppendingYearWhenNoQueryItemsAndYearIsNotNilReturnsURL),
    ]
}

extension URLTMDbTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTMDbTests = [
        ("testTMDbAPIBaseURLRetunsCorrectURL", testTMDbAPIBaseURLRetunsCorrectURL),
        ("testTMDbImageBaseURLRetunsCorrectURL", testTMDbImageBaseURLRetunsCorrectURL),
    ]
}

extension VideoCollectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VideoCollectionTests = [
        ("testDecodeReturnsVideoCollection", testDecodeReturnsVideoCollection),
    ]
}

extension VideoMetadataTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VideoMetadataTests = [
        ("testDecodeReturnsVideoCollection", testDecodeReturnsVideoCollection),
    ]
}

extension VideoSizeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VideoSizeTests = [
        ("test1080VideoSizeReturnsRawValue", test1080VideoSizeReturnsRawValue),
        ("test360VideoSizeReturnsRawValue", test360VideoSizeReturnsRawValue),
        ("test480VideoSizeReturnsRawValue", test480VideoSizeReturnsRawValue),
        ("test720VideoSizeReturnsRawValue", test720VideoSizeReturnsRawValue),
    ]
}

extension VideoTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VideoTypeTests = [
        ("testBehindTheScenesVideoTypeReturnsRawValue", testBehindTheScenesVideoTypeReturnsRawValue),
        ("testBloopersVideoTypeReturnsRawValue", testBloopersVideoTypeReturnsRawValue),
        ("testClipVideoTypeReturnsRawValue", testClipVideoTypeReturnsRawValue),
        ("testFeaturetteVideoTypeReturnsRawValue", testFeaturetteVideoTypeReturnsRawValue),
        ("testOpeningCreditsVideoTypeReturnsRawValue", testOpeningCreditsVideoTypeReturnsRawValue),
        ("testTeaserVideoTypeReturnsRawValue", testTeaserVideoTypeReturnsRawValue),
        ("testTrailerVideoTypeReturnsRawValue", testTrailerVideoTypeReturnsRawValue),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APIConfigurationTests.__allTests__APIConfigurationTests),
        testCase(BackdropURLProvidingTests.__allTests__BackdropURLProvidingTests),
        testCase(CastMemberTests.__allTests__CastMemberTests),
        testCase(CertificationTests.__allTests__CertificationTests),
        testCase(CertificationsDTOTests.__allTests__CertificationsDTOTests),
        testCase(CertificationsEndpointTests.__allTests__CertificationsEndpointTests),
        testCase(ConfigurationEndpointTests.__allTests__ConfigurationEndpointTests),
        testCase(CrewMemberTests.__allTests__CrewMemberTests),
        testCase(DataFormatterTMDbTests.__allTests__DataFormatterTMDbTests),
        testCase(DiscoverEndpointTests.__allTests__DiscoverEndpointTests),
        testCase(GenderTests.__allTests__GenderTests),
        testCase(GenreTests.__allTests__GenreTests),
        testCase(ImageCollectionTests.__allTests__ImageCollectionTests),
        testCase(ImageMetadataTests.__allTests__ImageMetadataTests),
        testCase(ImagesConfigurationTests.__allTests__ImagesConfigurationTests),
        testCase(JSONDecoderTMDbTests.__allTests__JSONDecoderTMDbTests),
        testCase(LogoURLProvidingTests.__allTests__LogoURLProvidingTests),
        testCase(MediaPageableListDTOTests.__allTests__MediaPageableListDTOTests),
        testCase(MediaTests.__allTests__MediaTests),
        testCase(MoviePageableListDTOTests.__allTests__MoviePageableListDTOTests),
        testCase(MovieSortByTests.__allTests__MovieSortByTests),
        testCase(MovieTests.__allTests__MovieTests),
        testCase(MoviesEndpointTests.__allTests__MoviesEndpointTests),
        testCase(NetworkTests.__allTests__NetworkTests),
        testCase(PageableListResultTests.__allTests__PageableListResultTests),
        testCase(PeopleEndpointTests.__allTests__PeopleEndpointTests),
        testCase(PersonCombinedCreditsTests.__allTests__PersonCombinedCreditsTests),
        testCase(PersonImageCollectionDTOTests.__allTests__PersonImageCollectionDTOTests),
        testCase(PersonMovieCreditsDTOTests.__allTests__PersonMovieCreditsDTOTests),
        testCase(PersonPageableListDTOTests.__allTests__PersonPageableListDTOTests),
        testCase(PersonTVShowCreditsTests.__allTests__PersonTVShowCreditsTests),
        testCase(PersonTests.__allTests__PersonTests),
        testCase(PosterURLProvidingTests.__allTests__PosterURLProvidingTests),
        testCase(ProductionCompanyTests.__allTests__ProductionCompanyTests),
        testCase(ProductionCountryTests.__allTests__ProductionCountryTests),
        testCase(ProfileURLProvidingTests.__allTests__ProfileURLProvidingTests),
        testCase(ReviewPageableListDTOTests.__allTests__ReviewPageableListDTOTests),
        testCase(ReviewTests.__allTests__ReviewTests),
        testCase(SearchEndpointTests.__allTests__SearchEndpointTests),
        testCase(ShowCreditsTests.__allTests__ShowCreditsTests),
        testCase(ShowTests.__allTests__ShowTests),
        testCase(SpokenLanguageTests.__allTests__SpokenLanguageTests),
        testCase(StatusTests.__allTests__StatusTests),
        testCase(StillURLProvidingTests.__allTests__StillURLProvidingTests),
        testCase(TMDbAPIAPIKeyTests.__allTests__TMDbAPIAPIKeyTests),
        testCase(TMDbAPICertificationTests.__allTests__TMDbAPICertificationTests),
        testCase(TMDbAPIClientTests.__allTests__TMDbAPIClientTests),
        testCase(TMDbAPIConifgurationTests.__allTests__TMDbAPIConifgurationTests),
        testCase(TMDbAPIDiscoverTests.__allTests__TMDbAPIDiscoverTests),
        testCase(TMDbAPIMovieTests.__allTests__TMDbAPIMovieTests),
        testCase(TMDbAPIPeopleTests.__allTests__TMDbAPIPeopleTests),
        testCase(TMDbAPISearchTests.__allTests__TMDbAPISearchTests),
        testCase(TMDbAPITVShowSeasonTests.__allTests__TMDbAPITVShowSeasonTests),
        testCase(TMDbAPITVShowTests.__allTests__TMDbAPITVShowTests),
        testCase(TMDbAPITrendingTests.__allTests__TMDbAPITrendingTests),
        testCase(TMDbCertificationServiceTests.__allTests__TMDbCertificationServiceTests),
        testCase(TMDbConfigurationServiceTests.__allTests__TMDbConfigurationServiceTests),
        testCase(TMDbDiscoverServiceTests.__allTests__TMDbDiscoverServiceTests),
        testCase(TMDbErrorTests.__allTests__TMDbErrorTests),
        testCase(TMDbMovieServiceTests.__allTests__TMDbMovieServiceTests),
        testCase(TMDbPersonServiceTests.__allTests__TMDbPersonServiceTests),
        testCase(TMDbSearchServiceTests.__allTests__TMDbSearchServiceTests),
        testCase(TMDbTVShowSeasonServiceTests.__allTests__TMDbTVShowSeasonServiceTests),
        testCase(TMDbTVShowServiceTests.__allTests__TMDbTVShowServiceTests),
        testCase(TMDbTrendingServiceTests.__allTests__TMDbTrendingServiceTests),
        testCase(TVShowEpisodeDTOTests.__allTests__TVShowEpisodeDTOTests),
        testCase(TVShowPageableListDTOTests.__allTests__TVShowPageableListDTOTests),
        testCase(TVShowSeaonsEndpointTests.__allTests__TVShowSeaonsEndpointTests),
        testCase(TVShowSeasonDTOTests.__allTests__TVShowSeasonDTOTests),
        testCase(TVShowSortByTests.__allTests__TVShowSortByTests),
        testCase(TVShowTests.__allTests__TVShowTests),
        testCase(TVShowsEndpointTests.__allTests__TVShowsEndpointTests),
        testCase(TrendingEndpointTests.__allTests__TrendingEndpointTests),
        testCase(TrendingTimeWindowFilterTypeTests.__allTests__TrendingTimeWindowFilterTypeTests),
        testCase(URLQueryItemTests.__allTests__URLQueryItemTests),
        testCase(URLTMDbTests.__allTests__URLTMDbTests),
        testCase(VideoCollectionTests.__allTests__VideoCollectionTests),
        testCase(VideoMetadataTests.__allTests__VideoMetadataTests),
        testCase(VideoSizeTests.__allTests__VideoSizeTests),
        testCase(VideoTypeTests.__allTests__VideoTypeTests),
    ]
}
#endif
