name: Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app

jobs:
  analysis:
    name: Analysis
    runs-on: macos-11

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: .sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analyse
        run: make analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
