name: Documentation CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/ci-documentation.yml"
      - "**/*.swift"
      - "**/*.docc/**/*.md"

concurrency:
  group: "ci-documentation-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  build-documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: 'echo "No build required"'
