name: Documentation CI

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci-documentation.yml"
      - "**/*.swift"
      - "**/*.docc/**/*.md"
  workflow_dispatch:

concurrency:
  group: "ci-documentation-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  build-documentation:
    name: Build Documentation
    runs-on: ubuntu-latest
    env:
      SWIFTCI_DOCC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: swift package generate-documentation --product TMDb
