name: Documentation CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "ci-documentation-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  build-documentation:
    name: Build Documentation
    runs-on: macos-14
    env:
      SWIFTCI_DOCC: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          set -o pipefail && NSUnbufferedIO=YES \
          swift package generate-documentation \
            --product TMDb 2>&1 | xcbeautify --renderer github-actions
