name: Code Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Every day at 12am
    - cron:  '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: "code-scan-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.1.app/Contents/Developer

jobs:
  codeScan:
    name: Code Scan
    runs-on: ubuntu-latest
    permissions:
        security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Scan
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sarif --output results.sarif || true'

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
