name: Integration

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/integration.yml"
      - "**/*.swift"

concurrency:
  group: "integration-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: 'echo "No test required"'
