name: Lint Markdown

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/lint-markdown.yml"
      - "README.md"
      - "**/*.docc/**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/lint-markdown.yml"
      - "README.md"
      - "**/*.docc/**/*.md"

concurrency:
  group: "lint-markdown-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: 'echo "No linting required"'
