name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/lint.yml"
      - "**/*.swift"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/lint.yml"
      - "**/*.swift"

concurrency:
  group: "lint-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  swiftlint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - name: Swiftlint
        run: 'echo "No linting required"'

  swiftformat:
    name: SwiftFormat
    runs-on: ubuntu-latest
    steps:
      - name: SwiftFormat
        run: 'echo "No linting required"'
