name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app

jobs:
  lint:
    name: Lint
    runs-on: macos-11
    concurrency: 
      group: pr-lint-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: swiftlint
        run: make lint

  test-on-macos:
    name: Test on macOS
    runs-on: macos-11
    concurrency: 
      group: pr-test-macos-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: make test-macos
  
  test-on-ios:
    name: Test on iOS
    runs-on: macos-11
    concurrency: 
      group: pr-test-ios-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      
      - name: Build and test
        run: make test-ios
  
  test-on-watchos:
    name: Test on watchOS
    runs-on: macos-11
    concurrency: 
      group: pr-test-watchos-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: make test-watchos
    
  test-on-appletv:
    name: Test on tvOS
    runs-on: macos-11
    concurrency: 
      group: pr-test-tvos-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: make test-tvos
  
  test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    concurrency: 
      group: pr-test-linux-${{ github.head_ref }}
      cancel-in-progress: true
    container:
      image: swift:5.5
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build and test
        run: make test-linux

  analysis:
    name: Analysis
    runs-on: macos-11
    concurrency: 
      group: pr-analysis-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: .sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analyse
        run: make analyse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
