name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer

    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: brew reinstall swiftlint

      - name: Lint
        run: swiftlint

      - name: Test
        run: xcrun swift test --enable-test-discovery --enable-code-coverage --sanitize=thread
